version: '3.8'
services:
  nginx:
    container_name: server-nginx
    image: nginx
    depends_on:
      - client
    restart: always
    volumes:
      - ./react-project/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      
  client:
    build: ./react-project
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./react-project:/app
    stdin_open: true
    tty: true

  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/

  nestjs-project:
    container_name: nestjs-project
    depends_on:
      - mysql-db
    build: ./nestjs-project
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_PROJECT_LOCAL_PORT:$NESTJS_PROJECT_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./nestjs-project:/app
      - /app/node_modules

volumes: 
  mysql-volume: